### PR TITLE
added things to whishlist

### PR DESCRIPTION
**Pull request by Drezil**
They said i could wish anything... so i did! :p

Should just be a simple merge, but i feel better not doing that all on my own :)

@NickSeagull @ocramz

### CODE REVIEW

**Comment by NickSeagull** [comment]
Looks cool for me :)

**Comment by ocramz** [comment]
@drezil : SOM stand for self-organizing maps right?could you use the full names when you first mention a new method?

**Comment by mdibaiee** [comment]
@drezil: I think it should be "Generative" neural networks

**Comment by Drezil** [comment]
i will fix that and push those 2 things :)

**Pull request merged**
